= Cheatsheets

[[VertxHawkularOptions]]
== VertxHawkularOptions

++++
 Vert.x Hawkular monitoring configuration.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[batchDelay]]`batchDelay`|`Number (int)`|
+++
@return the maximum delay between two consecutive batches
+++
|[[batchSize]]`batchSize`|`Number (int)`|
+++
@return the maximum number of metrics in a batch
+++
|[[enabled]]`enabled`|`Boolean`|-
|[[host]]`host`|`String`|
+++
@return the Hawkular Metrics service host
+++
|[[httpOptions]]`httpOptions`|`link:dataobjects.html#HttpClientOptions[HttpClientOptions]`|
+++
@return the configuration of the Hawkular Metrics HTTP client
+++
|[[metricsBridgeAddress]]`metricsBridgeAddress`|`String`|
+++
@return the metric bridge address. If enabled the metric bridge transfers metrics collected from the event bus to
 the Hawkular server. The metrics are sent as message on the event bus to the return address. The message is a
 JSON object specifying at least the <code>source</code> and <code>value</code> fields (<code>value</code> is a double).
+++
|[[metricsBridgeEnabled]]`metricsBridgeEnabled`|`Boolean`|
+++
Checks whether or not the metrics bridge is enabled.
+++
|[[metricsServiceUri]]`metricsServiceUri`|`String`|
+++
@return the Hawkular Metrics service URI
+++
|[[port]]`port`|`Number (int)`|
+++
@return the Hawkular Metrics service port
+++
|[[prefix]]`prefix`|`String`|
+++
@return the metric name prefix
+++
|[[schedule]]`schedule`|`Number (int)`|
+++
@return the metric collection interval (in seconds)
+++
|[[tenant]]`tenant`|`String`|
+++
@return the Hawkular tenant
+++
|===

