= Hawkular Metrics

This project is an implementation of the Vert.x Metrics Service Provider Interface (SPI): metrics built from Vert.x
events will be sent to Hawkular, an http://www.hawkular.org[open source monitoring and management solution].

== Features

* Vert.x core tools monitoring: TCP/HTTP client and servers, `link:../../groovydoc/io/vertx/groovy/core/datagram/DatagramSocket.html[DatagramSocket]`,
`link:../../groovydoc/io/vertx/groovy/core/eventbus/EventBus.html[EventBus]` and handlers
* User defined metrics via an `link:../../groovydoc/io/vertx/groovy/core/eventbus/EventBus.html[EventBus]` bridge.

== Getting started

The _vertx-hawkular-metrics_ module must be present in the classpath.

Maven users should add this to their project POM file:

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-hawkular-metrics</artifactId>
  <version>3.3.0-SNAPSHOT</version>
</dependency>
----

And Gradle users, to their build file:

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-hawkular-metrics:3.3.0-SNAPSHOT'
----

Vert.x does not enable SPI implementations by default. You must enable metric collection in the Vert.x options:

[source,groovy]
----
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx([
  metricsOptions:[
    enabled:true
  ]
])

----

== Configuration

=== Remote Hawkular server

By default, _vertx-hawkular-metrics_ sends metrics to a Hawkular server listening on `localhost` port `8080`.
But in production, the Hawkular server will likely run on a separate machine:

[source,groovy]
----
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx([
  metricsOptions:[
    enabled:true,
    host:"hawkular.example.com",
    port:8080
  ]
])

----

=== Server type

_vertx-hawkular-metrics_ is able to communicate with a standalone Hawkular Metrics server as well as a full-fledged Hawkular server.
Set the server type option to select your server flavor:

[source,groovy]
----
import io.vertx.ext.hawkular.ServerType
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx([
  metricsOptions:[
    enabled:true,
    serverType:ServerType.HAWKULAR
  ]
])

----

Standalone Metrics server is the default.

==== Tenant selection with a standalone Metrics server

Hawkular Metrics is a multi-tenant solution, and _vertx-hawkular-metrics_ can send metrics for a tenant other than `default`:

[source,groovy]
----
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx([
  metricsOptions:[
    enabled:true,
    standaloneMetricsOptions:[
      tenant:"sales-department"
    ]
  ]
])

----

==== Tenant selection and authentication with a Hawkular server

Requests sent to an Hawkular server must be authenticated:

[source,groovy]
----
import io.vertx.ext.hawkular.ServerType
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx([
  metricsOptions:[
    enabled:true,
    serverType:ServerType.HAWKULAR,
    hawkularServerOptions:[
      id:"username",
      secret:"password",
      tenant:"sales-department"
    ]
  ]
])

----

The tenant option may be omitted, and will default to `hawkular`.

=== HTTPS and other HTTP related options

_vertx-hawkular-metrics_ communicates with the Hawkular server over HTTP. In order to communicate over HTTPS, set the
`ssl` flag to true:

[source,groovy]
----
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx([
  metricsOptions:[
    enabled:true,
    host:"hawkular.example.com",
    port:443,
    httpOptions:[
      ssl:true
    ]
  ]
])

----

Note that all the usual `link:../../vertx-core/dataobjects.html#HttpClientOptions[HttpClientOptions]` properties can be used for SSL setup or client
tuning.

Please refer to `link:../dataobjects.html#VertxHawkularOptions[VertxHawkularOptions]` for an exhaustive list of options.

== Vert.x core tools metrics

This section lists all the metrics generated by monitoring the Vert.x core tools.

=== Net Client

[cols="15,50,35", options="header"]
|===
|Metric type
|Metric name
|Description

|Gauge
|`vertx.net.client.<host>:<port>.connections`
|Number of connections to the remote host currently opened.

|Counter
|`vertx.net.client.<host>:<port>.bytesReceived`
|Total number of bytes received from the remote host.

|Counter
|`vertx.net.client.<host>:<port>.bytesSent`
|Total number of bytes sent to the remote host.

|Counter
|`vertx.net.client.<host>:<port>.errorCount`
|Total number of errors.

|===

=== HTTP Client

[cols="15,50,35", options="header"]
|===
|Metric type
|Metric name
|Description

|Gauge
|`vertx.http.client.<host>:<port>.connections`
|Number of connections to the remote host currently opened.

|Counter
|`vertx.http.client.<host>:<port>.bytesReceived`
|Total number of bytes received from the remote host.

|Counter
|`vertx.http.client.<host>:<port>.bytesSent`
|Total number of bytes sent to the remote host.

|Counter
|`vertx.http.client.<host>:<port>.errorCount`
|Total number of errors.

|Gauge
|`vertx.http.client.<host>:<port>.requests`
|Number of requests waiting for a response.

|Counter
|`vertx.http.client.<host>:<port>.requestCount`
|Total number of requests sent.

|Counter
|`vertx.http.client.<host>:<port>.responseTime`
|Cumulated response time.

|Gauge
|`vertx.http.client.<host>:<port>.wsConnections`
|Number of websockets currently opened.

|===

=== Datagram socket

[cols="15,50,35", options="header"]
|===
|Metric type
|Metric name
|Description

|Counter
|`vertx.datagram.<host>:<port>.bytesReceived`
|Total number of bytes received on the `<host>:<port>` listening address.

|Counter
|`vertx.datagram.<host>:<port>.bytesSent`
|Total number of bytes sent to the remote host.

|Counter
|`vertx.datagram.errorCount`
|Total number of errors.

|===

=== Net Server

[cols="15,50,35", options="header"]
|===
|Metric type
|Metric name
|Description

|Gauge
|`vertx.net.server.<host>:<port>.connections`
|Number of opened connections to the Net Server listening on the `<host>:<port>` address.

|Counter
|`vertx.net.server.<host>:<port>.bytesReceived`
|Total number of bytes received by the Net Server listening on the `<host>:<port>` address.

|Counter
|`vertx.net.server.<host>:<port>.bytesSent`
|Total number of bytes sent to the Net Server listening on the `<host>:<port>` address.

|Counter
|`vertx.net.server.<host>:<port>.errorCount`
|Total number of errors.

|===

=== HTTP Server

[cols="15,50,35", options="header"]
|===
|Metric type
|Metric name
|Description

|Gauge
|`vertx.http.server.<host>:<port>.connections`
|Number of opened connections to the HTTP Server listening on the `<host>:<port>` address.

|Counter
|`vertx.http.server.<host>:<port>.bytesReceived`
|Total number of bytes received by the HTTP Server listening on the `<host>:<port>` address.

|Counter
|`vertx.http.server.<host>:<port>.bytesSent`
|Total number of bytes sent to the HTTP Server listening on the `<host>:<port>` address.

|Counter
|`vertx.http.server.<host>:<port>.errorCount`
|Total number of errors.

|Gauge
|`vertx.http.client.<host>:<port>.requests`
|Number of requests being processed.

|Counter
|`vertx.http.client.<host>:<port>.requestCount`
|Total number of requests processed.

|Counter
|`vertx.http.client.<host>:<port>.processingTime`
|Cumulated request processing time.

|Gauge
|`vertx.http.client.<host>:<port>.wsConnections`
|Number of websockets currently opened.

|===

=== Event Bus

[cols="15,50,35", options="header"]
|===
|Metric type
|Metric name
|Description

|Gauge
|`vertx.eventbus.handlers`
|Number of event bus handlers.

|Counter
|`vertx.eventbus.errorCount`
|Total number of errors.

|Counter
|`vertx.eventbus.bytesWritten`
|Total number of bytes sent while sending messages to event bus cluster peers.

|Counter
|`vertx.eventbus.bytesRead`
|Total number of bytes received while reading messages from event bus cluster peers.

|Gauge
|`vertx.eventbus.pending`
|Number of messages not processed yet. One message published will count for `N` pending if `N` handlers
are registered to the corresponding address.

|Gauge
|`vertx.eventbus.pendingLocal`
|Like `vertx.eventbus.pending`, for local messages only.

|Gauge
|`vertx.eventbus.pendingRemote`
|Like `vertx.eventbus.pending`, for remote messages only.

|Counter
|`vertx.eventbus.publishedMessages`
|Total number of messages published (publish / subscribe).

|Counter
|`vertx.eventbus.publishedLocalMessages`
|Like `vertx.eventbus.publishedMessages`, for local messages only.

|Counter
|`vertx.eventbus.publishedRemoteMessages`
|Like `vertx.eventbus.publishedMessages`, for remote messages only.

|Counter
|`vertx.eventbus.sentMessages`
|Total number of messages sent (point-to-point).

|Counter
|`vertx.eventbus.sentLocalMessages`
|Like `vertx.eventbus.sentMessages`, for local messages only.

|Counter
|`vertx.eventbus.sentRemoteMessages`
|Like `vertx.eventbus.sentMessages`, for remote messages only.

|Counter
|`vertx.eventbus.receivedMessages`
|Total number of messages received.

|Counter
|`vertx.eventbus.receivedLocalMessages`
|Like `vertx.eventbus.receivedMessages`, for remote messages only.

|Counter
|`vertx.eventbus.receivedRemoteMessages`
|Like `vertx.eventbus.receivedMessages`, for remote messages only.

|Counter
|`vertx.eventbus.deliveredMessages`
|Total number of messages delivered to handlers.

|Counter
|`vertx.eventbus.deliveredLocalMessages`
|Like `vertx.eventbus.deliveredMessages`, for remote messages only.

|Counter
|`vertx.eventbus.deliveredRemoteMessages`
|Like `vertx.eventbus.deliveredMessages`, for remote messages only.

|Counter
|`vertx.eventbus.replyFailures`
|Total number of message reply failures.

|Counter
|`vertx.eventbus.<address>.processingTime`
|Cumulated processing time for handlers listening to the `address`.

|===

== User defined metrics

Users can send their own metrics to the Hawkular server. In order to do so, the event bus metrics bridge must be
enabled:

[source,groovy]
----
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx([
  metricsOptions:[
    enabled:true,
    metricsBridgeEnabled:true
  ]
])

----

By default, the metrics bus handler is listening to the `hawkular.metrics` address. But the bridge address
can be configured:

[source,groovy]
----
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx([
  metricsOptions:[
    enabled:true,
    metricsBridgeEnabled:true,
    metricsBridgeAddress:"__hawkular_metrics"
  ]
])

----

The metrics bridge handler expects messages in the JSON format. The JSON object must at least provide a metric
`id` and a numerical `value`:

[source,groovy]
----
import groovy.transform.Field
@Field def vertx
def message = [
  id:"myapp.files.opened",
  value:7
]
vertx.eventBus().publish("metrics", message)

----

The handler will assume the metric is a gauge and will assign a timestamp corresponding to the time when the message
was processed. If the metric is a counter or if you prefer explicit configuration, set the `type` and
`timestamp` attributes:

[source,groovy]
----
import groovy.transform.Field
@Field def vertx
def message = [
  id:"myapp.files.opened",
  type:"counter",
  timestamp:189898098098908L,
  value:7
]
vertx.eventBus().publish("metrics", message)

----

Note that Hawkular understands all timestamps as milliseconds since January 1, 1970, 00:00:00 UTC.